### PR TITLE
Master add view diff truiz

### PR DESCRIPTION
**Pull request by ruiztulio**
This is the first version with the views and menus. All other options must be added to this module

### CODE REVIEW

**Comment by ruiztulio** [comment]
@Angelfentanez @mapuerta To this module is where you're going to integrate the remaining scripts (for the translations and the models)

**Comment by ruiztulio** [comment]
@moylop260 my idea is to have a tool that can work via web to view the changes and via command line:
cmd
views


The web interface is not developed yet, but the same script can send the results to the web and it will display them properly. What do you thinkl?

**Comment by nhomar** [comment]
On Fri, May 13, 2016 at 1:55 PM, Tulio Ruiz <notifications@github.com>
wrote:

> The web interface is not developed yet, but the same script can send the
> results to the web and it will display them properly. What do you thinkl?
>

It can be a simple controller.

copy the format of module instance_instrospection... where it will be
deployed can be see afterwards....




-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by ruiztulio** [comment]
@nhomar My idea is that this particular package does not depend on "where do you want to show" just to be a generate the results then it can be integrated with X or Y. 

By itself as a command will generate results on screen, maybe to a file or just spit the json output, then it can be used from any other app that you want (maybe the flask app that i was working on or an odoo module...)

**Pull request merged**
